MVC5Project.Web/Controllers/TeamController.cs
using System.Globalization;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MVC5Project.Domain.Model;
using System.Data.Entity;
using Microsoft.AspNet.Identity.EntityFramework;
using MVC5Project.Web.Models;
using System.Collections.Generic;
using System.IO;
using System.Data.Entity.Validation;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Kendo.Mvc;
using System.Web.Routing;
using System.Web.Script.Serialization;
using MVC5Project.Web.Code;


namespace MVC5Project.Web.Controllers
{
   // [Authorize]
    [OutputCache(Duration = 0, NoStore = true, VaryByParam = "*")]
    public class TeamController : Controller
    {
        DbMVC5ProjectEntities context = new DbMVC5ProjectEntities();
        //private static readonly IList<PlayerModel> customers = PlayerModel.GetAll();
        private static readonly IList<PlayerModel> customers;
        public static int PlayerId = 0;

        public static int NewBatchId = 0;
        public static int NewExcerciseid = 0;
        public TeamController()
        {
        }
        public TeamController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationSignInManager _signInManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set { _signInManager = value; }
        }

        public ActionResult Index()
        {
            return this.View(customers);
        }

        public ActionResult LaunchManualProposalWindow(int customerId)
        {
            RouteValueDictionary routeValues = this.GridRouteValues();
            PlayerModel dd = new PlayerModel();
            dd.Excercises = PlayerModel.GetCustomerTypeForCustomer(customerId);
            dd.AvailableExcercises = ExcerciseTypeViewModel.GetAll();
            // return this.RedirectToAction("Index", routeValues);
          
            return  this.PartialView("~/Views/Team/EditorTemplates/Customer.cshtml",dd);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Update(PlayerModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                // update in the databse


                //Deleting First All Records By Playerid
                //    var getRecordByplayerId = context.PlayerExcercises.Where(p => p.PlayerId == model.PlayerId).ToList();
                //    foreach (var item in getRecordByplayerId)
                //    {
                //        PlayerExcercise pla = context.PlayerExcercises.Find(item.Id);
                //        if (pla != null)
                //        {
                //            context.Entry(pla).State = EntityState.Deleted;
                //            context.SaveChanges();
                //        }
                //    }
                //    foreach (var item in model.PostedExcercises)
                //    {
                //        int ExcerciseID = Convert.ToInt32(item);
                //        PlayerExcercise pe = new PlayerExcercise();
                //        pe.ExcerciseId = ExcerciseID;
                //        pe.PlayerId = model.PlayerId;
                //        context.Entry(pe).State = EntityState.Added;
                //        context.SaveChanges();

                //    }
                //}
                //RouteValueDictionary routeValues = this.GridRouteValues();
                //return this.RedirectToAction("Index", routeValues);

                //// return this.RedirectToAction("Index", routeValues);
                //ViewData["postedCustomerTypes"] = model.PostedExcercises;
            }
            return this.View("Index");
        }
        /// <summary>
        /// Action Result for adding a player in the system
        /// </summary>
        /// <returns></returns>
        public ActionResult TeamPlayer(int? ID, string Message)
        {
            if (Request.QueryString["ID"] != null)
            {
                PlayerId = Convert.ToInt32(Request.QueryString["ID"]);
            }
            if (ID != null && ID != -1)
            {
                var orgid = context.UserDetails.FirstOrDefault(a => a.ID == ID);
                TempData["Message"] = Message;
                ViewBag.Orgid = orgid.OrgID;
            }
            else
            {
                var loggesdinUser = User.Identity.GetUserId();
                var GettingOrgnization = context.UserDetails.FirstOrDefault(a => a.UserId == loggesdinUser).OrgID;
                TempData["Message"] = Message;
                if (GettingOrgnization != null)
                {
                    ViewBag.Orgid = GettingOrgnization;
                }
            }

            return View();
        }
        [HttpPost]
        public ActionResult TeamPlayer(TeamViewModel model, int? hdnfilename)
        {

            Player oPlayer = new Player();
            string _finalPath = "";
            var _uploadImage = Request.Files[0];
            try
            {

                if (ModelState.IsValid)
                {  //Saveing the player Name to get PlayerID to save Player Image Within That Player'sID
                    oPlayer.PlayerFirstName = model.PlayerFirstName;
                    context.Players.Add(oPlayer);
                    context.SaveChanges();

                    //Getting PlayerID
                    var _playerResult = context.Players.Where(a => a.PlayerFirstName == model.PlayerFirstName).SingleOrDefault();
                    var _playerId = _playerResult.PlayerId;
                    oPlayer.OrgId = hdnfilename;
                    oPlayer.OrgStartDate = model.OrgStartDate;
                    oPlayer.PlayerEmailAddress = model.PlayerEmailAddress;

                    oPlayer.PlayerLastName = model.PlayerLastName;
                    oPlayer.PlayerNumber = model.PlayerNumber;
                    oPlayer.PlayerPhoneNumber = model.PlayerPhoneNumber;
                    oPlayer.DateOfBirth = model.DateOfBirth;
                    if (_uploadImage.ContentLength > 0)
                    {
                        string _fileExtention = Path.GetExtension(_uploadImage.FileName);
                        if (_fileExtention.ToLower().Contains(".jpg") || _fileExtention.ToLower().Contains(".png") || _fileExtention.ToLower().Contains(".gif") || _fileExtention.ToLower().Contains(".jpeg"))
                        {



                            //Making directory of Indvisual Player Based on their ID
                            string _fileName = Path.GetFileName(_uploadImage.FileName);
                            string _path = Server.MapPath("~/uploads/PlayerImages/" + _playerId + "/");
                            if (Directory.Exists(_path))
                            {

                                _uploadImage.SaveAs(_path + _fileName);
                            }
                            else
                            {
                                Directory.CreateDirectory(_path);
                                _uploadImage.SaveAs(_path + _fileName);
                            }
                            _finalPath = Path.Combine(_path, _fileName);

                            oPlayer.PlayerPicture = _playerId + "/" + _fileName;


                        }
                        else
                        {
                            TempData["Error"] = "You can only upload the Extention like .jpg, .png, .jpeg, .gif.";
                        }
                    }
                    context.Entry(oPlayer).State = EntityState.Modified;
                    context.SaveChanges();
                    ModelState.Clear();
                    model = null;
                    TempData["Message"] = "Player is saved successfully";
                    string Messa = TempData["Message"].ToString();
                    return RedirectToAction("TeamPlayer", new { ID = PlayerId, Message = Messa });
                }
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }

            return View(model);
        }
        /// <summary>
        /// Page For Saving Athlete Detail
        /// </summary>
        /// <returns></returns>
        public ActionResult IndividualAtheleteProfile()
        {
            return View();
        }


        /// <summary>
        /// 20 October
        /// </summary>
        /// <returns></returns>
        /// 
        public ActionResult Customers_Read([DataSourceRequest]DataSourceRequest request)
        {
            var loggedinUser = User.Identity.GetUserId();
            int? orgId = 0;
            string role = "";

MVC5Project.Web/Views/Shared/_DatetimeEditorTemplate.cshtml
@using Kendo.Mvc.UI
@model MVC5Project.Web.Models.PlayerInfoViewModel


@*@(Html.Kendo().DatePickerFor(m=>m.)
                  .Name("DateOfBirth")
                .Value(Model == null ? DateTime.Now : @Model)
                .Format("MM/dd/yyyy")
)*@
@(Html.Kendo().DatePickerFor(m => m.DateOfBirth).Format("dd/MM/yyyy"))

MVC5Project.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    
    <link href="~/Scripts/jtable/themes/metro/lightgray/jtable.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.9.2.js"></script>
    <script src="~/Scripts/jtable/jquery.jtable.js"></script>
    <script src="~/Scripts/jquery.validationEngine.js"></script>
    <script src="~/Scripts/jquery.validationEngine-en.js"></script>
    <link href="~/Content/validationEngine.jquery.css" rel="stylesheet" />

    @*<link href="@Url.Content("~/Content/kendo/2014.2.1008/kendo.common.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2014.2.1008/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2014.2.1008/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2014.2.1008/kendo.default.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2014.2.1008/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/kendo/2014.2.1008/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2014.2.1008/kendo.all.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2014.2.1008/kendo.aspnetmvc.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated == true && (User.IsInRole("System Admin")))
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        @*<li>@Html.ActionLink("Manage Users", "About", "Home")</li>*@
                        @if (User.IsInRole("Client Admin"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Client Administrator<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    @*<li><a href="#">Add Users</a></li>*@
                                    <li><a href="/Home/Users">Manage users</a></li>
                                </ul>
                            </li>
                        }

                        @if (User.IsInRole("System Admin"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">system administration<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="/Home/Organizations">Organizations</a></li>
                                    <li><a href="/Home/NewClient">Add New Client</a></li>
                                    <li><a href="/Home/SystemAdminUsers">Manage users</a></li>
                                    <li><a href="/Home/RegisterdUsers">Registerd Users</a></li>
                                </ul>
                            </li>
                        }
                        @if (!User.IsInRole("System Admin"))
                        {
                            <li>@Html.ActionLink("Edit Profile", "EditProfile", "Home")</li>
                        }
                        @*<li>@Html.ActionLink("Reset Password", "Manage", "Account")</li>*@
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

MVC5Project.Web/Views/Shared/_Layout3.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="front-page no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Physmodo | A Revolutionary Physical Therapy Platform</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <script src="~/Scripts/js/jquery.min.js"></script>
    @*<script src="/Scripts/jquery-2.1.0.js"></script>*@

    <script src="~/Scripts/js/TweenMax.min.js"></script>
    <script src="~/Scripts/js/jquery.scrollmagic.js"></script>

    <script src="~/Scripts/js/ScrollToPlugin.min.js"></script>
    <script src="~/Scripts/js/selectnav.min.js"></script>

    <script src="~/Scripts/js/ready.js"></script>
    <script src="~/Scripts/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    @*<script src="~/Scripts/js/physmodo.js"></script>*@


    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap-glyphicons.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />
    <link href="~/Content/css/app-backgrounds.css" rel="stylesheet" />


    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Scripts/jtable/themes/metro/lightgray/jtable.css" rel="stylesheet" />
    @*<link href="/Scripts/jtable/themes/metro/blue/jtable.css" rel="stylesheet" type="text/css">*@
    <script src="~/Scripts/jquery-ui-1.9.2.js"></script>
    <script src="~/Scripts/jtable/jquery.jtable.js"></script>
    <script src="~/Scripts/jquery.validationEngine.js"></script>
    <script src="~/Scripts/jquery.validationEngine-en.js"></script>
    <link href="~/Content/validationEngine.jquery.css" rel="stylesheet" />
    @*@Styles.Render("~/bundles/css")*@

    @*<link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/responsive.css">
        <link rel="stylesheet" href="css/bootstrap-theme.min.css">
        <link href="css/bootstrap-glyphicons.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <link rel="stylesheet" type="text/css" href="css/app-backgrounds.css">*@
    <link href='http://fonts.googleapis.com/css?family=Exo+2:300,400,500,600,600italic,700' rel='stylesheet' type='text/css'>
    <script>
        //domready(function(){
        //	selectnav('nav', {
        //	label: '--Navigation--'});
        //	prettyPrint()
        //})

    </script>
    <style>
        #btn_btn_default {
            margin-right: -56%;
            margin-bottom: 1%;
        }

        #Center_Part {
            width: 19%;
            float: left;
            text-align: left;
        }

        #Right_part {
            float: right;
            width: 80%;
        }





        .dropdown-menu {
            position: absolute;
            top: 100%;
            left: 0;
            z-index: 1000;
            display: none;
            float: left;
            min-width: 136px;
            padding: 5px 0;
            margin: 2px 0 0;
            list-style: none;
            font-size: 14px;
            background-color: #fff;
            border: 1px solid #ccc;
            border: 1px solid rgba(0,0,0,.15);
            border-radius: 4px;
            -webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);
            box-shadow: 0 6px 12px rgba(0,0,0,.175);
            background-clip: padding-box;
        }

            .dropdown-menu li {
                opacity: 1 !important;
            }

            .dropdown-menu > li > a {
                color: white !important;
            }
    </style>



</head>
<body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <div class="scroll_wrapper" id='scroll_wrapper'>
        <div class="bg1-container bg1-intro">
            <div class="bg1-background"></div>
            <div class="navbar navbar-inverse navbar-fixed-top" style="background: none; border: none;">
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                Hello @User.Identity.GetUserName()!
                                @*@Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage", style = "color:black; padding-right:10px" })*@
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()" style="color:black; padding-right:20px">Log off</a></li>
                        </ul>
                    }
                }
                @*<form action="/Account/LogOff" class="navbar-right" id="logoutForm" method="post">
                        <input name="__RequestVerificationToken" type="hidden" value="-w-0WZXgJ3S1q4PVwNRZ4O95emYLeQYFrf0idcLgjX57KlDIpddfc2r5cU3SwIcxy_8RdDWzoWlms3ZE1UE-U-8pJf6OmLUv6Gm6IIyAB42GP_mzNhzgnHdFMVcQvtDOGhdAyUsZHngeR8W9wLxsWA2">        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="/Manage" title="Manage" style="color:black; padding-right:10px">Hello @User.Identity.GetUserName()!</a>
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()" style="color:black; padding-right:20px">Log off</a></li>
                        </ul>
                    </form>*@
            </div>
            <div class="row">
                <div class="col-md-2 left-logo">
                    <a href="/">
                        <img src="~/Content/images/physmodo-logo.png" class="physmodo-logo img-responsive">
                    </a>

                </div>
                <div class="col-md-12 physmodo-logo">
                    <h1>A Revolutionary Physical Therapy Platform</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2" style="width: 20%;">
                    <div class="left-sidebar">
                        <ul class="" id="nav">
                            @if (Request.IsAuthenticated == true)
                            {
                                <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
                                <li>@Html.ActionLink("About", "About", "Home")</li>
                                @*<li>@Html.ActionLink("PlayerExcercise", "Index", "Team")</li>*@
                                <li><a href="/Team/ManagePlayers">Manage Players</a></li>
                                @*<li><a href="/Team/Measurement">Add Measurements</a></li>*@
                                <li><a href="/Team/AlertAndRisk">Alert/Risk</a></li>
                                <li><a href="/Team/Reports">Reports</a></li>
                                @*<li><a href="/Team/AlertsModule">AlertsModule</a></li>*@
                                <li><a href="/Team/ActivityReport">Activity Report</a></li>
                                if (User.IsInRole("Client Admin"))
                                {
                                    <li>@Html.ActionLink("Edit Profile", "EditProfile", "Home")</li>
                                    <li><a href="/API/Index">API</a></li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Client Administrator<span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            @*<li><a href="#">Add Users</a></li>*@
                                            <li><a href="/Home/Users">Manage Users</a></li>
                                            <li><a href="/Team/TeamPlayer?ID=-1">Add Player</a></li>

                                        </ul>
                                    </li>
                                }

                                if (User.IsInRole("System Admin"))
                                {
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">system administration<span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="/Home/Organizations">Organizations</a></li>
                                            <li><a href="/Home/NewClient">Add New Client</a></li>
                                            <li><a href="/Home/SystemAdminUsers">Manage users</a></li>
                                            <li><a href="/Home/RegisterdUsers">Registerd Users</a></li>
                                        </ul>
                                    </li>

                                    @*<li><a href="/Home/Organizations">Organizations</a></li>
                                        <li><a href="/Home/NewClient">Add New Client</a></li>
                                        <li><a href="/Home/SystemAdminUsers">Manage users</a></li>
                                        <li><a href="/Home/RegisterdUsers">Registerd Users</a></li>*@

                                }
                                if (!User.IsInRole("System Admin") && User.IsInRole("client standard user"))
                                {
                                    <li>@Html.ActionLink("Edit Profile", "EditProfile", "Home")</li>
                                    <li><a href="/Team/TeamPlayer?ID=-1">Add Player</a></li>


                                    @*<li><a href="/Team/Measurement">Measurement</a></li>*@
                                }

                            }


                            @*@Html.Partial("_LoginPartial")*@
                        </ul>

                    </div>


                </div>

                <div class="col-md-12" style="float: left; width: 75%;">
                    <div class="HeroArea">
                        @RenderBody()

                    </div>
                </div>
            </div>
            <footer>
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 text-center">

                            <img class="logo" src="~/Content/images/footer-logo.png">

                            <p><span>copyright Physmodo, Inc.</span> </p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="http://physmodo.com/wp-content/themes/twentytwelve-child/js/vendor/jquery-1.11.0.min.js"><\/script>')</script>

        @*<script src="js/vendor/bootstrap.min.js"></script>*@
        <script src="~/Scripts/js/bootstrap.min.js"></script>>

        <script src="http://physmodo.com/wp-content/themes/twentytwelve-child/js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function (b, o, i, l, e, r) {
                b.GoogleAnalyticsObject = l; b[l] || (b[l] =
                function () { (b[l].q = b[l].q || []).push(arguments) }); b[l].l = +new Date;
                e = o.createElement(i); r = o.getElementsByTagName(i)[0];
                e.src = 'http://www.google-analytics.com/analytics.js';
                r.parentNode.insertBefore(e, r)
            }(window, document, 'script', 'ga'));
            ga('create', 'UA-XXXXX-X'); ga('send', 'pageview');
        </script>

    </div>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.js"></script>

    @RenderSection("scripts", required: false)
    <link href="@Url.Content("~/Content/kendo/2014.2.1008/kendo.common.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2014.2.1008/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2014.2.1008/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2014.2.1008/kendo.default.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2014.2.1008/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
    @*<script src="@Url.Content("~/Scripts/kendo/2014.2.1008/jquery.min.js")"></script>*@
    <script src="@Url.Content("~/Scripts/kendo/2014.2.1008/kendo.all.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2014.2.1008/kendo.aspnetmvc.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</body>

</html>